apiVersion: v1
kind: LimitRange
metadata:
      name: testlimit
      namespace: testns
spec:
    limits:
        - default:
             cpu: 200m
             memory: 500M
          defaultRequest:
             cpu: 100m
             memory: 150M
          type: Container
