apiVersion: v1
kind: Pod
metadata:
     name: mypod1
     labels:
         type: devpod
spec:
   containers:
           - name: my-container
             image: nginx
             resources:
                   requests:
                       memory: 250Mi
                       cpu: 0.1
                   limits:
                       cpu: 0.5
                       memory: 500Mi
