https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

apiVersion: v1
kind: ResourceQuota
metadata:
        name: myquota
spec:
   hard:
      pods: 2
      requests.cpu: 0.5
      requests.memory: 500Mi
      limits.cpu: 1
      limits.memory: 1Gi
