---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    lbl1: myrs

spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - myapp1
          - myapp2
    template:
      metadata:
        name: pod1
        labels:
          app: myapp1
          name: pod
      spec:
        containers:
          - image: nginx
            name: my-container

